export const GET_VARIANTS_QUERY_INITIATE = "GET_VARIANTS_QUERY_INITIATE";
export const GET_VARIANTS_QUERY_SUCCESS = "GET_VARIANTS_QUERY_SUCCESS";
export const GET_VARIANTS_QUERY_FAIL = "GET_VARIANTS_QUERY_FAIL";
